// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmgvjkfddijuayrgrkrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZ3Zqa2ZkZGlqdWF5cmdya3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDQxMTUsImV4cCI6MjA3NDE4MDExNX0.POz_Q0JX65N3Sj8JK2qhdpmFXakCnkeiDBR3LqPm1aE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});